### ISSUE TITLE
ReCaptcha with multiple forms on the same page

### ISSUE THREAD

**Issue by JakoD** [pixelant/pxa_form_enhancement#17]
**Situation:**
There are 2 forms on the same page each having an ReCaptcha element.

**Expected:**
In the frontend, for each form the ReCaptcha element is shown

**Actual:**
Only the first form has the element shown, the second one has an empty container <div>.

**Comment by JakoD** [comment]
The root for this issue seems located in `InitRecaptchaViewHelper::render()`, which calls `PageRenderer::addJsFooterInlineCode()` with `'pxa_form_enhancement'` as first argument. Any further call to this will be treated as already added and thus will be ignored. This way any ReCaptcha element but the first will be missing it's initializer script.

Edit: Just extending the identifier won't work, since then the callback for ReCaptcha will be overridden with the one of the last form's element.

**Comment by anjeylink** [comment]
This is fixed, but forms has it's own bug where it doesn't go through validators for multiple forms on one page. Only first form get validated
