### ISSUE TITLE
Remove captcha value from submit page / mail

### ISSUE THREAD

**Issue by michelemerlo** [pixelant/pxa_form_enhancement#7]
My client wanted to have a captcha integrated into his form and I used your extension pxa_form_enhancement to make it possible. Now he also wants to have the value "passed successfully" from the captcha removed from the submit page / mail that gets sent. Is there a way to hide the value or configure which values get passed?
Thanks a lot in advance

PS: I'm using typo3 8.7.4

**Comment by anjeylink** [comment]
Hi, you can probably change path to "sysext/form/Resources/Private/Frontend/Partials/SummaryPage.html" and exclude recaptcha in foreach. i can take a deeper look on this later.

**Comment by michelemerlo** [comment]
Hi, thanks a lot already.
I think you mean this foreach-loop:
```
<f:for each="{formValue.processedValue}" as="value">
        <li>{value}</li>
</f:for>
```
But to exclude Rechaptcha, I'd need to know the identifier for it.
